/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufscar.dc.lince.tvanytime.core;

import java.util.Collection;
import java.util.Collections;
import java.util.Hashtable;
import java.util.Vector;

/**
 *
 * @author lince
 */
public class TVAnytimeGenreToolboxExtended {

    private static Hashtable tableGenre;

    public TVAnytimeGenreToolboxExtended() {
    }

    public static Collection getGenres() {
        Collection col = tableGenre.values();
        Vector data=new Vector();
        data.addAll(col);
        Collections.sort(data);
        return data;
    }

    //called when initializing class
    static {
        //tableGenre to store TVAnytime genres
        tableGenre = new Hashtable(800);

        // Intention tableGenre
        tableGenre.put("1", "Intention");
        tableGenre.put("1.1", "Intention.Entertainment");
        tableGenre.put("1.1.1", "Intention.Entertainment.Pure entertainment");
        tableGenre.put("1.1.2", "Intention.Entertainment.Informative entertainment");
        tableGenre.put("1.2", "Intention.Information");
        tableGenre.put("1.2.1", "Intention.Information.Government");
        tableGenre.put("1.2.2", "Intention.Information.Pure information");
        tableGenre.put("1.2.3", "Intention.Information.Infotainment");
        tableGenre.put("1.2.4", "Intention.Information.Advice");
        tableGenre.put("1.3", "Intention.Education");
        tableGenre.put("1.3.1", "Intention.Education.Schools Programmes");
        tableGenre.put("1.3.1.1", "Intention.Education.Schools Programmes.Primary");
        tableGenre.put("1.3.1.2", "Intention.Education.Schools Programmes.Secondary");
        tableGenre.put("1.3.1.3", "Intention.Education.Schools Programmes.Tertiary");
        tableGenre.put("1.3.2", "Intention.Education.Lifelong/Further education");
        tableGenre.put("1.4", "Intention.Promotional");
        tableGenre.put("1.5", "Intention.Advertising");
        tableGenre.put("1.6", "Intention.Retail");
        tableGenre.put("1.7", "Intention.Fund-raising");
        tableGenre.put("1.8", "Intention.Enrichment");
        tableGenre.put("1.8.1", "Intention.Enrichment.General enrichment");
        tableGenre.put("1.8.2", "Intention.Enrichment.Inspirational enrichment");

        // Format tableGenre
        tableGenre.put("2", "Format");
        tableGenre.put("2.1", "Format.Structured");
        tableGenre.put("2.1.1", "Format.Structured.Bulletin");
        tableGenre.put("2.1.2", "Format.Structured.Magazine");
        tableGenre.put("2.1.3", "Format.Structured.Commented event");
        tableGenre.put("2.1.4", "Format.Structured.Documentary");
        tableGenre.put("2.1.5", "Format.Structured.Discussion/Interview/Debate");
        tableGenre.put("2.1.6", "Format.Structured.Lecture/Speech/Presentation");
        tableGenre.put("2.1.7", "Format.Structured.Textual (incl, relayed teletext)");
        tableGenre.put("2.1.8", "Format.Structured.Phone-in");
        tableGenre.put("2.1.9", "Format.Structured.DJ with discs");
        tableGenre.put("2.2", "Format.Representation/Play");
        tableGenre.put("2.2.1", "Format.Representation/Play.Fictional portrayal of life");
        tableGenre.put("2.2.2", "Format.Representation/Play.Readings");
        tableGenre.put("2.2.3", "Format.Representation/Play.Representation with puppets");
        tableGenre.put("2.3", "Format.Cartoon/Animation");
        tableGenre.put("2.3.1", "Format.Cartoon/Animation.Anime");
        tableGenre.put("2.3.2", "Format.Cartoon/Animation.Computer");
        tableGenre.put("2.3.3", "Format.Cartoon/Animation.Cartoon");
        tableGenre.put("2.4", "Format.Show");
        tableGenre.put("2.4.1", "Format.Show.Hosted show");
        tableGenre.put("2.4.1.1", "Format.Show.Hosted show.Simple game show");
        tableGenre.put("2.4.1.2", "Format.Show.Hosted show.Big game show");
        tableGenre.put("2.4.2", "Format.Show.Panel-show");
        tableGenre.put("2.4.2.1", "Format.Show.Panel-show.Simple game show");
        tableGenre.put("2.4.2.2", "Format.Show.Panel-show.Big game show");
        tableGenre.put("2.4.3", "Format.Show.Non-hosted show");
        tableGenre.put("2.4.4", "Format.Show.Standup comedian(s)");
        tableGenre.put("2.5", "Format.Artistic performance");
        tableGenre.put("2.7", "Format.Interactive");
        tableGenre.put("2.7.1", "Format.Interactive.Local Interactivity");
        tableGenre.put("2.7.1.1", "Format.Interactive.Local Interactivity.Static informational");
        tableGenre.put("2.7.1.2", "Format.Interactive.Local Interactivity.Dynamic informational");
        tableGenre.put("2.7.1.3", "Format.Interactive.Local Interactivity.Viewing chats");
        tableGenre.put("2.7.1.4", "Format.Interactive.Local Interactivity.Quiz - basic multiple choice");
        tableGenre.put("2.7.1.5", "Format.Interactive.Local Interactivity.Quiz - text or number entry answers");
        tableGenre.put("2.7.1.6", "Format.Interactive.Local Interactivity.Re-ordering");
        tableGenre.put("2.7.1.7", "Format.Interactive.Local Interactivity.Positional");
        tableGenre.put("2.7.1.8", "Format.Interactive.Local Interactivity.Sync quiz");
        tableGenre.put("2.7.1.9", "Format.Interactive.Local Interactivity.Timer quiz");
        tableGenre.put("2.7.1.10", "Format.Interactive.Local Interactivity.Elimination and timer");
        tableGenre.put("2.7.1.11", "Format.Interactive.Local Interactivity.Categories");
        tableGenre.put("2.7.1.12", "Format.Interactive.Local Interactivity.Level based quiz/game");
        tableGenre.put("2.7.1.13", "Format.Interactive.Local Interactivity.Following a sequence");
        tableGenre.put("2.7.1.14", "Format.Interactive.Local Interactivity.Local multi player");
        tableGenre.put("2.7.1.15", "Format.Interactive.Local Interactivity.Multi stream audio-video");
        tableGenre.put("2.7.1.16", "Format.Interactive.Local Interactivity.Enhanced advertisement");
        tableGenre.put("2.7.1.17", "Format.Interactive.Local Interactivity.Logic based games");
        tableGenre.put("2.7.1.18", "Format.Interactive.Local Interactivity.Word games");
        tableGenre.put("2.7.1.19", "Format.Interactive.Local Interactivity.Positional games");
        tableGenre.put("2.7.1.20", "Format.Interactive.Local Interactivity.Board games");
        tableGenre.put("2.7.1.21", "Format.Interactive.Local Interactivity.Text based gaming");
        tableGenre.put("2.7.1.22", "Format.Interactive.Local Interactivity.Dynamic 2D/3D graphics");
        tableGenre.put("2.7.2", "Format.Interactive.Intermittent Response");
        tableGenre.put("2.7.2.1", "Format.Interactive.Intermittent Response.Single impulse vote");
        tableGenre.put("2.7.2.2", "Format.Interactive.Intermittent Response.Impulse vote from choices");
        tableGenre.put("2.7.2.3", "Format.Interactive.Intermittent Response.Impulse Yes/No vote");
        tableGenre.put("2.7.2.4", "Format.Interactive.Intermittent Response.Impulse vote with a value");
        tableGenre.put("2.7.2.5", "Format.Interactive.Intermittent Response.Submit answers/form");
        tableGenre.put("2.7.2.6", "Format.Interactive.Intermittent Response.SMS using mobile");
        tableGenre.put("2.7.2.7", "Format.Interactive.Intermittent Response.SMS using TV remote");
        tableGenre.put("2.7.2.8", "Format.Interactive.Intermittent Response.Impulse gambling");
        tableGenre.put("2.7.2.9", "Format.Interactive.Intermittent Response.Impulse transaction");
        tableGenre.put("2.7.2.10", "Format.Interactive.Intermittent Response.Multi player TS networked services/games");
        tableGenre.put("2.7.2.11", "Format.Interactive.Intermittent Response.Interactive advertisement");
        tableGenre.put("2.7.3", "Format.Interactive.Always on connection");
        tableGenre.put("2.7.3.1", "Format.Interactive.Always on connection.Chat Forum");
        tableGenre.put("2.7.3.2", "Format.Interactive.Always on connection.Chat Forum via web");
        tableGenre.put("2.7.3.3", "Format.Interactive.Always on connection.Threaded mail discussions");
        tableGenre.put("2.7.3.4", "Format.Interactive.Always on connection.Point to point");
        tableGenre.put("2.7.3.5", "Format.Interactive.Always on connection.3rd party point to point");
        tableGenre.put("2.7.3.6", "Format.Interactive.Always on connection.Voice chat using mic capability");
        tableGenre.put("2.7.3.7", "Format.Interactive.Always on connection.Dual player networked services/games");
        tableGenre.put("2.7.3.8", "Format.Interactive.Always on connection.Multi player RT networked services/games");
        tableGenre.put("2.7.3.9", "Format.Interactive.Always on connection.Gambling services");
        tableGenre.put("2.7.3.10", "Format.Interactive.Always on connection.Impulse transaction");
        tableGenre.put("2.7.3.11", "Format.Interactive.Always on connection.Non-linear audio-video");

        // Content tableGenre
        tableGenre.put("3", "Content");
        tableGenre.put("3.1", "Content.Non-Fiction");
        tableGenre.put("3.1.1", "Content.Non-Fiction.News");
        tableGenre.put("3.1.1.1", "Content.Non-Fiction.News.Daily news");
        tableGenre.put("3.1.1.2", "Content.Non-Fiction.News.Special news/edition");
        tableGenre.put("3.1.1.3", "Content.Non-Fiction.News.Special Reports");
        tableGenre.put("3.1.1.4", "Content.Non-Fiction.News.Commentary");
        tableGenre.put("3.1.1.5", "Content.Non-Fiction.News.Periodical/General");
        tableGenre.put("3.1.1.6", "Content.Non-Fiction.News.National politics/National Assembly");
        tableGenre.put("3.1.1.7", "Content.Non-Fiction.News.Economy/Market/Financial/Business");
        tableGenre.put("3.1.1.8", "Content.Non-Fiction.News.Foreign/International");
        tableGenre.put("3.1.1.9", "Content.Non-Fiction.News.Sports");
        tableGenre.put("3.1.1.10", "Content.Non-Fiction.News.Cultural");
        tableGenre.put("3.1.1.11", "Content.Non-Fiction.News.Local/regional");
        tableGenre.put("3.1.1.12", "Content.Non-Fiction.News.Traffic");
        tableGenre.put("3.1.1.13", "Content.Non-Fiction.News.Weather forecasts");
        tableGenre.put("3.1.1.14", "Content.Non-Fiction.News.Service information");
        tableGenre.put("3.1.1.15", "Content.Non-Fiction.News.Public Affairs");
        tableGenre.put("3.1.1.16", "Content.Non-Fiction.News.Current affairs");
        tableGenre.put("3.1.2", "Content.Non-Fiction.Philosophies of life");
        tableGenre.put("3.1.2.1", "Content.Non-Fiction.Philosophies of life.Religion");
        tableGenre.put("3.1.2.1.1", "Content.Non-Fiction.Philosophies of life.Religion.Buddhism");
        tableGenre.put("3.1.2.1.2", "Content.Non-Fiction.Philosophies of life.Religion.Hinduism");
        tableGenre.put("3.1.2.1.3", "Content.Non-Fiction.Philosophies of life.Religion.Christianity");
        tableGenre.put("3.1.2.1.4", "Content.Non-Fiction.Philosophies of life.Religion.Islam");
        tableGenre.put("3.1.2.1.5", "Content.Non-Fiction.Philosophies of life.Religion.Judaism");
        tableGenre.put("3.1.2.1.6", "Content.Non-Fiction.Philosophies of life.Religion.Atheism");
        tableGenre.put("3.1.2.1.7", "Content.Non-Fiction.Philosophies of life.Religion.Agnosticism");
        tableGenre.put("3.1.2.1.8", "Content.Non-Fiction.Philosophies of life.Religion.Shintoism");
        tableGenre.put("3.1.2.2", "Content.Non-Fiction.Philosophies of life.Non-religious philosophies");
        tableGenre.put("3.1.2.2.1", "Content.Non-Fiction.Philosophies of life.Non-religious philosophies.Communism");
        tableGenre.put("3.1.2.2.2", "Content.Non-Fiction.Philosophies of life.Non-religious philosophies.Humanism");
        tableGenre.put("3.1.2.2.3", "Content.Non-Fiction.Philosophies of life.Non-religious philosophies.Capitalism");
        tableGenre.put("3.1.2.2.4", "Content.Non-Fiction.Philosophies of life.Non-religious philosophies.Socialism");
        tableGenre.put("3.1.2.2.5", "Content.Non-Fiction.Philosophies of life.Non-religious philosophies.Libertarianism");
        tableGenre.put("3.1.2.2.6", "Content.Non-Fiction.Philosophies of life.Non-religious philosophies.Republicanism");
        tableGenre.put("3.1.3", "Content.Non-Fiction.General non-fiction");
        tableGenre.put("3.1.3.1", "Content.Non-Fiction.General non-fiction.Political");
        tableGenre.put("3.1.3.2", "Content.Non-Fiction.General non-fiction.Social");
        tableGenre.put("3.1.3.3", "Content.Non-Fiction.General non-fiction.Economic");
        tableGenre.put("3.1.3.4", "Content.Non-Fiction.General non-fiction.Legal");
        tableGenre.put("3.1.3.5", "Content.Non-Fiction.General non-fiction.Finance");
        tableGenre.put("3.1.3.6", "Content.Non-Fiction.General non-fiction.Education");
        tableGenre.put("3.1.3.7", "Content.Non-Fiction.General non-fiction.International affairs");
        tableGenre.put("3.1.3.8", "Content.Non-Fiction.General non-fiction.Military/Defence");
        tableGenre.put("3.1.4", "Content.Non-Fiction.Arts & Media");
        tableGenre.put("3.1.4.1", "Content.Non-Fiction.Arts & Media.Music");
        tableGenre.put("3.1.4.2", "Content.Non-Fiction.Arts & Media.Dance");
        tableGenre.put("3.1.4.3", "Content.Non-Fiction.Arts & Media.Theatre");
        tableGenre.put("3.1.4.4", "Content.Non-Fiction.Arts & Media.Opera");
        tableGenre.put("3.1.4.5", "Content.Non-Fiction.Arts & Media.Cinema");
        tableGenre.put("3.1.4.6", "Content.Non-Fiction.Arts & Media.Advertising");
        tableGenre.put("3.1.4.7", "Content.Non-Fiction.Arts & Media.Press");
        tableGenre.put("3.1.4.8", "Content.Non-Fiction.Arts & Media.Plastic Arts");
        tableGenre.put("3.1.4.9", "Content.Non-Fiction.Arts & Media.Fine arts");
        tableGenre.put("3.1.4.10", "Content.Non-Fiction.Arts & Media.Experimental arts");
        tableGenre.put("3.1.4.11", "Content.Non-Fiction.Arts & Media.Architecture");
        tableGenre.put("3.1.4.12", "Content.Non-Fiction.Arts & Media.Showbiz");
        tableGenre.put("3.1.4.13", "Content.Non-Fiction.Arts & Media.Television");
        tableGenre.put("3.1.4.14", "Content.Non-Fiction.Arts & Media.Radio");
        tableGenre.put("3.1.4.15", "Content.Non-Fiction.Arts & Media.New media");
        tableGenre.put("3.1.5", "Content.Non-Fiction.Humanities");
        tableGenre.put("3.1.5.1", "Content.Non-Fiction.Humanities.Literature");
        tableGenre.put("3.1.5.2", "Content.Non-Fiction.Humanities.Languages");
        tableGenre.put("3.1.5.3", "Content.Non-Fiction.Humanities.History");
        tableGenre.put("3.1.5.4", "Content.Non-Fiction.Humanities.Culture/tradition/anthropology/Ethnic studies");
        tableGenre.put("3.1.5.5", "Content.Non-Fiction.Humanities.War/Conflict");
        tableGenre.put("3.1.6", "Content.Non-Fiction.Sciences");
        tableGenre.put("3.1.6.1", "Content.Non-Fiction.Sciences.Applied sciences");
        tableGenre.put("3.1.6.2", "Content.Non-Fiction.Sciences.Nature/natural sciences");
        tableGenre.put("3.1.6.3", "Content.Non-Fiction.Sciences.Animals/Wildlife");
        tableGenre.put("3.1.6.4", "Content.Non-Fiction.Sciences.Environment/geography");
        tableGenre.put("3.1.6.5", "Content.Non-Fiction.Sciences.Space/Universe");
        tableGenre.put("3.1.6.6", "Content.Non-Fiction.Sciences.Physical sciences");
        tableGenre.put("3.1.6.7", "Content.Non-Fiction.Sciences.Medecine");
        tableGenre.put("3.1.6.8", "Content.Non-Fiction.Sciences.Technology");
        tableGenre.put("3.1.6.9", "Content.Non-Fiction.Sciences.Physiology");
        tableGenre.put("3.1.6.10", "Content.Non-Fiction.Sciences.Psychology");
        tableGenre.put("3.1.6.11", "Content.Non-Fiction.Sciences.Social");
        tableGenre.put("3.1.6.12", "Content.Non-Fiction.Sciences.Spiritual");
        tableGenre.put("3.1.6.13", "Content.Non-Fiction.Sciences.Mathematics");
        tableGenre.put("3.1.6.14", "Content.Non-Fiction.Sciences.Archaeology");
        tableGenre.put("3.1.7", "Content.Non-Fiction.Human interest");
        tableGenre.put("3.1.7.1", "Content.Non-Fiction.Human interest.Reality");
        tableGenre.put("3.1.7.2", "Content.Non-Fiction.Human interest.Society/Show business/Gossip");
        tableGenre.put("3.1.7.3", "Content.Non-Fiction.Human interest.Biography/notable personalities");
        tableGenre.put("3.1.7.4", "Content.Non-Fiction.Human interest.Personal problems");
        tableGenre.put("3.1.7.5", "Content.Non-Fiction.Human interest.Investigative journalism");
        tableGenre.put("3.1.7.6", "Content.Non-Fiction.Human interest.Museums");
        tableGenre.put("3.1.7.7", "Content.Non-Fiction.Human interest.Religious buildings");
        tableGenre.put("3.1.8", "Content.Non-Fiction.Transport and Communications");
        tableGenre.put("3.1.8.1", "Content.Non-Fiction.Transport and Communications.Air");
        tableGenre.put("3.1.8.2", "Content.Non-Fiction.Transport and Communications.Land");
        tableGenre.put("3.1.8.3", "Content.Non-Fiction.Transport and Communications.Sea");
        tableGenre.put("3.1.8.4", "Content.Non-Fiction.Transport and Communications.Space");
        tableGenre.put("3.1.9", "Content.Non-Fiction.Events");
        tableGenre.put("3.1.9.1", "Content.Non-Fiction.Events.Anniversary");
        tableGenre.put("3.1.9.2", "Content.Non-Fiction.Events.Fair");
        tableGenre.put("3.1.9.3", "Content.Non-Fiction.Events.Tradeshow");
        tableGenre.put("3.1.9.4", "Content.Non-Fiction.Events.Musical");
        tableGenre.put("3.1.9.5", "Content.Non-Fiction.Events.Exhibition");
        tableGenre.put("3.2", "Content.Sports");
        tableGenre.put("3.2.1", "Content.Sports.Athletics");
        tableGenre.put("3.2.1.1", "Content.Sports.Athletics.Field");
        tableGenre.put("3.2.1.2", "Content.Sports.Athletics.Track");
        tableGenre.put("3.2.1.3", "Content.Sports.Athletics.Combined athletics");
        tableGenre.put("3.2.1.4", "Content.Sports.Athletics.Running");
        tableGenre.put("3.2.1.5", "Content.Sports.Athletics.Cross-country");
        tableGenre.put("3.2.1.6", "Content.Sports.Athletics.Triathlon");
        tableGenre.put("3.2.2", "Content.Sports.Cycling/bicycle");
        tableGenre.put("3.2.2.1", "Content.Sports.Cycling/bicycle.Mountainbike");
        tableGenre.put("3.2.2.2", "Content.Sports.Cycling/bicycle.Bicross");
        tableGenre.put("3.2.2.3", "Content.Sports.Cycling/bicycle.Indoor cycling");
        tableGenre.put("3.2.2.4", "Content.Sports.Cycling/bicycle.Road Cycling");
        tableGenre.put("3.2.3", "Content.Sports.Team sports");
        tableGenre.put("3.2.3.1", "Content.Sports.Team sports.Football (American)");
        tableGenre.put("3.2.3.2", "Content.Sports.Team sports.Football (Australian)");
        tableGenre.put("3.2.3.3", "Content.Sports.Team sports.Football (Gaelic)");
        tableGenre.put("3.2.3.4", "Content.Sports.Team sports.Football (Indoor)");
        tableGenre.put("3.2.3.5", "Content.Sports.Team sports.Beach soccer");
        tableGenre.put("3.2.3.6", "Content.Sports.Team sports.Bandy");
        tableGenre.put("3.2.3.7", "Content.Sports.Team sports.Baseball");
        tableGenre.put("3.2.3.8", "Content.Sports.Team sports.Basketball");
        tableGenre.put("3.2.3.9", "Content.Sports.Team sports.Cricket");
        tableGenre.put("3.2.3.10", "Content.Sports.Team sports.Croquet");
        tableGenre.put("3.2.3.11", "Content.Sports.Team sports.Faustball");
        tableGenre.put("3.2.3.12", "Content.Sports.Team sports.Football (soccer)");
        tableGenre.put("3.2.3.13", "Content.Sports.Team sports.Handball");
        tableGenre.put("3.2.3.14", "Content.Sports.Team sports.Hockey");
        tableGenre.put("3.2.3.15", "Content.Sports.Team sports.Korfball");
        tableGenre.put("3.2.3.16", "Content.Sports.Team sports.Lacrosse");
        tableGenre.put("3.2.3.17", "Content.Sports.Team sports.Netball");
        tableGenre.put("3.2.3.18", "Content.Sports.Team sports.Roller skating");
        tableGenre.put("3.2.3.19", "Content.Sports.Team sports.Rugby");
        tableGenre.put("3.2.3.19.1", "Content.Sports.Team sports.Rugby.Rugby union");
        tableGenre.put("3.2.3.19.2", "Content.Sports.Team sports.Rugby.Rugby league");
        tableGenre.put("3.2.3.20", "Content.Sports.Team sports.Softball");
        tableGenre.put("3.2.3.21", "Content.Sports.Team sports.Volleyball");
        tableGenre.put("3.2.3.22", "Content.Sports.Team sports.Beach volley");
        tableGenre.put("3.2.3.23", "Content.Sports.Team sports.Hurling");
        tableGenre.put("3.2.4", "Content.Sports.Racket sports");
        tableGenre.put("3.2.4.1", "Content.Sports.Racket sports.Badminton");
        tableGenre.put("3.2.4.2", "Content.Sports.Racket sports.Racketball");
        tableGenre.put("3.2.4.3", "Content.Sports.Racket sports.Short tennis");
        tableGenre.put("3.2.4.4", "Content.Sports.Racket sports.Soft tennis");
        tableGenre.put("3.2.4.5", "Content.Sports.Racket sports.Squash");
        tableGenre.put("3.2.4.6", "Content.Sports.Racket sports.Table tennis");
        tableGenre.put("3.2.4.7", "Content.Sports.Racket sports.Tennis");
        tableGenre.put("3.2.5", "Content.Sports.Martial Arts");
        tableGenre.put("3.2.5.1", "Content.Sports.Martial Arts.Aikido");
        tableGenre.put("3.2.5.2", "Content.Sports.Martial Arts.Jai-alai");
        tableGenre.put("3.2.5.3", "Content.Sports.Martial Arts.Judo");
        tableGenre.put("3.2.5.4", "Content.Sports.Martial Arts.Ju-jitsu");
        tableGenre.put("3.2.5.5", "Content.Sports.Martial Arts.Karate");
        tableGenre.put("3.2.5.6", "Content.Sports.Martial Arts.Sumo/Fighting games");
        tableGenre.put("3.2.5.7", "Content.Sports.Martial Arts.Sambo");
        tableGenre.put("3.2.5.8", "Content.Sports.Martial Arts.Taekwondo");
        tableGenre.put("3.2.6", "Content.Sports.Water sports");
        tableGenre.put("3.2.6.1", "Content.Sports.Water sports.Bodyboarding");
        tableGenre.put("3.2.6.2", "Content.Sports.Water sports.Yatching");
        tableGenre.put("3.2.6.3", "Content.Sports.Water sports.Canoeing");
        tableGenre.put("3.2.6.4", "Content.Sports.Water sports.Diving");
        tableGenre.put("3.2.6.5", "Content.Sports.Water sports.Fishing");
        tableGenre.put("3.2.6.6", "Content.Sports.Water sports.Polo");
        tableGenre.put("3.2.6.7", "Content.Sports.Water sports.Rowing");
        tableGenre.put("3.2.6.8", "Content.Sports.Water sports.Sailing");
        tableGenre.put("3.2.6.9", "Content.Sports.Water sports.Sub-aquatics");
        tableGenre.put("3.2.6.10", "Content.Sports.Water sports.Surfing");
        tableGenre.put("3.2.6.11", "Content.Sports.Water sports.Swimming");
        tableGenre.put("3.2.6.12", "Content.Sports.Water sports.Water polo");
        tableGenre.put("3.2.6.13", "Content.Sports.Water sports.Water sking");
        tableGenre.put("3.2.6.14", "Content.Sports.Water sports.Windsurfing");
        tableGenre.put("3.2.7", "Content.Sports.Winter sports");
        tableGenre.put("3.2.7.1", "Content.Sports.Winter sports.Bobsleigh/tobogganing");
        tableGenre.put("3.2.7.2", "Content.Sports.Winter sports.Curling");
        tableGenre.put("3.2.7.3", "Content.Sports.Winter sports.Ice-hockey");
        tableGenre.put("3.2.7.4", "Content.Sports.Winter sports.Ice-skating");
        tableGenre.put("3.2.7.5", "Content.Sports.Winter sports.Luge");
        tableGenre.put("3.2.7.6", "Content.Sports.Winter sports.Skating");
        tableGenre.put("3.2.7.7", "Content.Sports.Winter sports.Skibob");
        tableGenre.put("3.2.7.8", "Content.Sports.Winter sports.Skiing");
        tableGenre.put("3.2.7.9", "Content.Sports.Winter sports.Sleddog");
        tableGenre.put("3.2.7.10", "Content.Sports.Winter sports.Snowboarding");
        tableGenre.put("3.2.7.11", "Content.Sports.Winter sports.Alpine skiing");
        tableGenre.put("3.2.7.12", "Content.Sports.Winter sports.Freestyle skiing");
        tableGenre.put("3.2.7.13", "Content.Sports.Winter sports.inline skating");
        tableGenre.put("3.2.7.14", "Content.Sports.Winter sports.Nordic skiing");
        tableGenre.put("3.2.7.15", "Content.Sports.Winter sports.Ski jumping");
        tableGenre.put("3.2.7.16", "Content.Sports.Winter sports.Speed skating");
        tableGenre.put("3.2.7.17", "Content.Sports.Winter sports.Figure skating");
        tableGenre.put("3.2.7.18", "Content.Sports.Winter sports.Ice-dance");
        tableGenre.put("3.2.7.19", "Content.Sports.Winter sports.Marathon");
        tableGenre.put("3.2.7.20", "Content.Sports.Winter sports.Short-track");
        tableGenre.put("3.2.7.21", "Content.Sports.Winter sports.Biathlon");
        tableGenre.put("3.2.8", "Content.Sports.Motor sports");
        tableGenre.put("3.2.8.1", "Content.Sports.Motor sports.Motor/auto racing");
        tableGenre.put("3.2.8.2", "Content.Sports.Motor sports.Motor boating/motor racing");
        tableGenre.put("3.2.8.3", "Content.Sports.Motor sports.Motor cycling");
        tableGenre.put("3.2.8.4", "Content.Sports.Motor sports.Formula 1");
        tableGenre.put("3.2.8.5", "Content.Sports.Motor sports.Indy car");
        tableGenre.put("3.2.8.6", "Content.Sports.Motor sports.Karting");
        tableGenre.put("3.2.8.7", "Content.Sports.Motor sports.Rally");
        tableGenre.put("3.2.8.8", "Content.Sports.Motor sports.Trucking");
        tableGenre.put("3.2.8.9", "Content.Sports.Motor sports.Tractor Pulling");
        tableGenre.put("3.2.8.10", "Content.Sports.Motor sports.Auto racing");
        tableGenre.put("3.2.9", "Content.Sports.Social sports");
        tableGenre.put("3.2.9.1", "Content.Sports.Social sports.Billiards");
        tableGenre.put("3.2.9.2", "Content.Sports.Social sports.Boules");
        tableGenre.put("3.2.9.3", "Content.Sports.Social sports.Bowling");
        tableGenre.put("3.2.9.4", "Content.Sports.Social sports.Chess");
        tableGenre.put("3.2.9.5", "Content.Sports.Social sports.Dance sport");
        tableGenre.put("3.2.9.6", "Content.Sports.Social sports.Darts");
        tableGenre.put("3.2.9.7", "Content.Sports.Social sports.Pool");
        tableGenre.put("3.2.9.8", "Content.Sports.Social sports.Snooker");
        tableGenre.put("3.2.9.9", "Content.Sports.Social sports.Tug-of-war");
        tableGenre.put("3.2.9.10", "Content.Sports.Social sports.Balle Pelote");
        tableGenre.put("3.2.9.11", "Content.Sports.Social sports.Basque Pelote");
        tableGenre.put("3.2.9.12", "Content.Sports.Social sports.Trickshot");
        tableGenre.put("3.2.10", "Content.Sports.Gymnastics");
        tableGenre.put("3.2.10.1", "Content.Sports.Gymnastics.Assymetric bars");
        tableGenre.put("3.2.10.2", "Content.Sports.Gymnastics.Beam");
        tableGenre.put("3.2.10.3", "Content.Sports.Gymnastics.Horse");
        tableGenre.put("3.2.10.4", "Content.Sports.Gymnastics.Mat");
        tableGenre.put("3.2.10.5", "Content.Sports.Gymnastics.Parallel bars");
        tableGenre.put("3.2.10.6", "Content.Sports.Gymnastics.Rings");
        tableGenre.put("3.2.10.7", "Content.Sports.Gymnastics.Trampoline");
        tableGenre.put("3.2.11", "Content.Sports.Equestrian");
        tableGenre.put("3.2.11.1", "Content.Sports.Equestrian.Cart");
        tableGenre.put("3.2.11.2", "Content.Sports.Equestrian.Dressage");
        tableGenre.put("3.2.11.3", "Content.Sports.Equestrian.Horse racing");
        tableGenre.put("3.2.11.4", "Content.Sports.Equestrian.Polo");
        tableGenre.put("3.2.11.5", "Content.Sports.Equestrian.Jumping");
        tableGenre.put("3.2.11.6", "Content.Sports.Equestrian.Crossing");
        tableGenre.put("3.2.11.7", "Content.Sports.Equestrian.Trotting");
        tableGenre.put("3.2.12", "Content.Sports.Adventure sports");
        tableGenre.put("3.2.12.1", "Content.Sports.Adventure sports.Archery");
        tableGenre.put("3.2.12.2", "Content.Sports.Adventure sports.Extreme sports");
        tableGenre.put("3.2.12.3", "Content.Sports.Adventure sports.Mountaineering");
        tableGenre.put("3.2.12.4", "Content.Sports.Adventure sports.Climbing");
        tableGenre.put("3.2.12.5", "Content.Sports.Adventure sports.Orienteering");
        tableGenre.put("3.2.12.6", "Content.Sports.Adventure sports.Shooting");
        tableGenre.put("3.2.12.7", "Content.Sports.Adventure sports.Sport acrobatics");
        tableGenre.put("3.2.12.8", "Content.Sports.Adventure sports.Rafting");
        tableGenre.put("3.2.13", "Content.Sports.Strength-based sports");
        tableGenre.put("3.2.13.1", "Content.Sports.Strength-based sports.Body-building");
        tableGenre.put("3.2.13.2", "Content.Sports.Strength-based sports.Boxing");
        tableGenre.put("3.2.13.3", "Content.Sports.Strength-based sports.Combative sports");
        tableGenre.put("3.2.13.4", "Content.Sports.Strength-based sports.Power-lifting");
        tableGenre.put("3.2.13.5", "Content.Sports.Strength-based sports.Weight-lifting");
        tableGenre.put("3.2.13.6", "Content.Sports.Strength-based sports.Wrestling");
        tableGenre.put("3.2.14", "Content.Sports.Air sports");
        tableGenre.put("3.2.14.1", "Content.Sports.Air sports.Ballooning");
        tableGenre.put("3.2.14.2", "Content.Sports.Air sports.Hang gliding");
        tableGenre.put("3.2.14.3", "Content.Sports.Air sports.Sky diving");
        tableGenre.put("3.2.14.4", "Content.Sports.Air sports.Delta-plane");
        tableGenre.put("3.2.14.5", "Content.Sports.Air sports.Parachuting");
        tableGenre.put("3.2.14.6", "Content.Sports.Air sports.Kiting");
        tableGenre.put("3.2.14.7", "Content.Sports.Air sports.Aeronautics");
        tableGenre.put("3.2.14.8", "Content.Sports.Air sports.Gliding");
        tableGenre.put("3.2.14.9", "Content.Sports.Air sports.Flying");
        tableGenre.put("3.2.14.10", "Content.Sports.Air sports.Aerobatics");
        tableGenre.put("3.2.15", "Content.Sports.Golf");
        tableGenre.put("3.2.16", "Content.Sports.Fencing");
        tableGenre.put("3.2.17", "Content.Sports.Dog racing");
        tableGenre.put("3.2.18", "Content.Sports.Casting");
        tableGenre.put("3.2.19", "Content.Sports.Maccabi");
        tableGenre.put("3.2.20", "Content.Sports.Modern Pantathlon");
        tableGenre.put("3.2.21", "Content.Sports.Sombo");
        tableGenre.put("3.3", "Content.Leisure/Hobby");
        tableGenre.put("3.3.1", "Content.Leisure/Hobby.Do-it-yourself");
        tableGenre.put("3.3.2", "Content.Leisure/Hobby.Cookery");
        tableGenre.put("3.3.3", "Content.Leisure/Hobby.Gardening");
        tableGenre.put("3.3.4", "Content.Leisure/Hobby.Travel/Tourism");
        tableGenre.put("3.3.5", "Content.Leisure/Hobby.Adventure/Expeditions");
        tableGenre.put("3.3.6", "Content.Leisure/Hobby.Fishing");
        tableGenre.put("3.3.7", "Content.Leisure/Hobby.Outdoor ");
        tableGenre.put("3.3.8", "Content.Leisure/Hobby.Pet");
        tableGenre.put("3.3.9", "Content.Leisure/Hobby.Craft/Handicraft ");
        tableGenre.put("3.3.10", "Content.Leisure/Hobby.Art");
        tableGenre.put("3.3.11", "Content.Leisure/Hobby.Music");
        tableGenre.put("3.3.12", "Content.Leisure/Hobby.Board Games");
        tableGenre.put("3.3.13", "Content.Leisure/Hobby.Computer Games");
        tableGenre.put("3.3.14", "Content.Leisure/Hobby.Card Cames");
        tableGenre.put("3.3.15", "Content.Leisure/Hobby.Fitness/Keep-fit");
        tableGenre.put("3.3.16", "Content.Leisure/Hobby.Personal health");
        tableGenre.put("3.3.17", "Content.Leisure/Hobby.Car");
        tableGenre.put("3.3.18", "Content.Leisure/Hobby.Motorcycle/Motoring");
        tableGenre.put("3.3.19", "Content.Leisure/Hobby.Fashion");
        tableGenre.put("3.3.20", "Content.Leisure/Hobby.Life/House Keeping/Lifestyle ");
        tableGenre.put("3.3.21", "Content.Leisure/Hobby.Technology/Computing");
        tableGenre.put("3.3.22", "Content.Leisure/Hobby.Gaming");
        tableGenre.put("3.3.23", "Content.Leisure/Hobby.Shopping");
        tableGenre.put("3.3.24", "Content.Leisure/Hobby.Adult");
        tableGenre.put("3.3.25", "Content.Leisure/Hobby.Road safety");
        tableGenre.put("3.3.26", "Content.Leisure/Hobby.Consumer advice");
        tableGenre.put("3.3.27", "Content.Leisure/Hobby.Employment Advice");
        tableGenre.put("3.3.28", "Content.Leisure/Hobby.Boating");
        tableGenre.put("3.3.29", "Content.Leisure/Hobby.Parenting");
        tableGenre.put("3.3.30", "Content.Leisure/Hobby.Self-help");
        tableGenre.put("3.3.31", "Content.Leisure/Hobby.Collectibles");
        tableGenre.put("3.3.32", "Content.Leisure/Hobby.Jewelry");
        tableGenre.put("3.3.33", "Content.Leisure/Hobby.Beauty");
        tableGenre.put("3.3.34", "Content.Leisure/Hobby.Aviation");
        tableGenre.put("3.4", "Content.Fiction");
        tableGenre.put("3.4.1", "Content.Fiction.General light drama");
        tableGenre.put("3.4.2", "Content.Fiction.Soap");
        tableGenre.put("3.4.2.1", "Content.Fiction.Soap.Soap Opera");
        tableGenre.put("3.4.2.2", "Content.Fiction.Soap.Soap Special");
        tableGenre.put("3.4.2.3", "Content.Fiction.Soap.Soap Talk");
        tableGenre.put("3.4.3", "Content.Fiction.Romance");
        tableGenre.put("3.4.4", "Content.Fiction.Legal melodrama");
        tableGenre.put("3.4.5", "Content.Fiction.Medical melodrama");
        tableGenre.put("3.4.6", "Content.Fiction.Action");
        tableGenre.put("3.4.6.1", "Content.Fiction.Action.Adventure");
        tableGenre.put("3.4.6.2", "Content.Fiction.Action.Disaster");
        tableGenre.put("3.4.6.3", "Content.Fiction.Action.Mystery");
        tableGenre.put("3.4.6.4", "Content.Fiction.Action.Detective");
        tableGenre.put("3.4.6.5", "Content.Fiction.Action.Historical/Epic");
        tableGenre.put("3.4.6.6", "Content.Fiction.Action.Horror");
        tableGenre.put("3.4.6.7", "Content.Fiction.Action.Science fiction");
        tableGenre.put("3.4.6.8", "Content.Fiction.Action.War");
        tableGenre.put("3.4.6.9", "Content.Fiction.Action.Western");
        tableGenre.put("3.4.6.10", "Content.Fiction.Action.Thriller");
        tableGenre.put("3.4.6.11", "Content.Fiction.Action.Sports");
        tableGenre.put("3.4.6.12", "Content.Fiction.Action.Martial arts");
        tableGenre.put("3.4.6.13", "Content.Fiction.Action.Epic");
        tableGenre.put("3.4.7", "Content.Fiction.Fantasy/Fairy tale");
        tableGenre.put("3.4.8", "Content.Fiction.Erotica");
        tableGenre.put("3.4.9", "Content.Fiction.Drama based on real events (docudrama)");
        tableGenre.put("3.4.10", "Content.Fiction.Musical");
        tableGenre.put("3.4.11", "Content.Fiction.Comedy");
        tableGenre.put("3.4.12", "Content.Fiction.Effect movies");
        tableGenre.put("3.4.13", "Content.Fiction.Classical drama");
        tableGenre.put("3.4.14", "Content.Fiction.Period drama");
        tableGenre.put("3.4.15", "Content.Fiction.Contemporary drama");
        tableGenre.put("3.4.16", "Content.Fiction.Religious");
        tableGenre.put("3.4.17", "Content.Fiction.Poems/Stories");
        tableGenre.put("3.4.18", "Content.Fiction.Biography");
        tableGenre.put("3.4.19", "Content.Fiction.Psychological drama");
        tableGenre.put("3.5", "Content.Amusement");
        tableGenre.put("3.5.1", "Content.Amusement.Game show");
        tableGenre.put("3.5.2", "Content.Amusement.Quiz/Contest");
        tableGenre.put("3.5.3", "Content.Amusement.Variety show");
        tableGenre.put("3.5.4", "Content.Amusement.Surprise show");
        tableGenre.put("3.5.5", "Content.Amusement.Reality show");
        tableGenre.put("3.5.6", "Content.Amusement.Candid camera");
        tableGenre.put("3.5.7", "Content.Amusement.Comedy");
        tableGenre.put("3.5.7.1", "Content.Amusement.Comedy.Broken comedy");
        tableGenre.put("3.5.7.2", "Content.Amusement.Comedy.Romantic comedy");
        tableGenre.put("3.5.7.3", "Content.Amusement.Comedy.Sitcom");
        tableGenre.put("3.5.7.4", "Content.Amusement.Comedy.Satire");
        tableGenre.put("3.5.8", "Content.Amusement.Standup comedian(s)");
        tableGenre.put("3.5.9", "Content.Amusement.Humour");
        tableGenre.put("3.5.10", "Content.Amusement.Magic/Hypnotism");
        tableGenre.put("3.5.11", "Content.Amusement.Circus");
        tableGenre.put("3.5.12", "Content.Amusement.Dating show");
        tableGenre.put("3.5.13", "Content.Amusement.Bullfighting");
        tableGenre.put("3.5.14", "Content.Amusement.Rodeo");
        tableGenre.put("3.5.15", "Content.Amusement.Airshow");
        tableGenre.put("3.6", "Content.Music and Dance");
        tableGenre.put("3.6.1", "Content.Music and Dance.Classical music");
        tableGenre.put("3.6.1.1", "Content.Music and Dance.Classical music.Early");
        tableGenre.put("3.6.1.2", "Content.Music and Dance.Classical music.Classical");
        tableGenre.put("3.6.1.3", "Content.Music and Dance.Classical music.Romantic");
        tableGenre.put("3.6.1.4", "Content.Music and Dance.Classical music.Contemporary");
        tableGenre.put("3.6.1.5", "Content.Music and Dance.Classical music.Light classical");
        tableGenre.put("3.6.1.6", "Content.Music and Dance.Classical music.Middle Ages");
        tableGenre.put("3.6.1.7", "Content.Music and Dance.Classical music.Renaissance");
        tableGenre.put("3.6.1.8", "Content.Music and Dance.Classical music.Baroque");
        tableGenre.put("3.6.1.9", "Content.Music and Dance.Classical music.Opera");
        tableGenre.put("3.6.1.10", "Content.Music and Dance.Classical music.Solo instruments");
        tableGenre.put("3.6.1.11", "Content.Music and Dance.Classical music.Chamber");
        tableGenre.put("3.6.1.12", "Content.Music and Dance.Classical music.Symphonic");
        tableGenre.put("3.6.1.13", "Content.Music and Dance.Classical music.Vocal");
        tableGenre.put("3.6.1.14", "Content.Music and Dance.Classical music.Choral");
        tableGenre.put("3.6.2", "Content.Music and Dance.Jazz");
        tableGenre.put("3.6.2.1", "Content.Music and Dance.Jazz.New Orleans/early jazz");
        tableGenre.put("3.6.2.2", "Content.Music and Dance.Jazz.Big band/Swing/Dixie");
        tableGenre.put("3.6.2.3", "Content.Music and Dance.Jazz.Blues/Soul jazz");
        tableGenre.put("3.6.2.4", "Content.Music and Dance.Jazz.Bop/Hard bop/Bebop");
        tableGenre.put("3.6.2.5", "Content.Music and Dance.Jazz.Traditional/Smooth");
        tableGenre.put("3.6.2.6", "Content.Music and Dance.Jazz.Cool/Free");
        tableGenre.put("3.6.2.7", "Content.Music and Dance.Jazz.Modern/Acid/Avant-garde");
        tableGenre.put("3.6.2.8", "Content.Music and Dance.Jazz.Latin & World jazz");
        tableGenre.put("3.6.2.9", "Content.Music and Dance.Jazz.Pop jazz/Jazz funk");
        tableGenre.put("3.6.2.10", "Content.Music and Dance.Jazz.Acid jazz/fusion");
        tableGenre.put("3.6.3", "Content.Music and Dance.Background music");
        tableGenre.put("3.6.3.1", "Content.Music and Dance.Background music.Middle-of-the-road");
        tableGenre.put("3.6.3.2", "Content.Music and Dance.Background music.Easy listening");
        tableGenre.put("3.6.3.3", "Content.Music and Dance.Background music.Ambient");
        tableGenre.put("3.6.3.4", "Content.Music and Dance.Background music.Mood music");
        tableGenre.put("3.6.3.5", "Content.Music and Dance.Background music.Oldies");
        tableGenre.put("3.6.3.6", "Content.Music and Dance.Background music.Love songs");
        tableGenre.put("3.6.3.7", "Content.Music and Dance.Background music.Dance hall");
        tableGenre.put("3.6.3.8", "Content.Music and Dance.Background music.Soundtrack");
        tableGenre.put("3.6.3.9", "Content.Music and Dance.Background music.Trailer");
        tableGenre.put("3.6.3.10", "Content.Music and Dance.Background music.Showtunes");
        tableGenre.put("3.6.3.11", "Content.Music and Dance.Background music.TV");
        tableGenre.put("3.6.3.12", "Content.Music and Dance.Background music.Cabaret");
        tableGenre.put("3.6.3.13", "Content.Music and Dance.Background music.Instrumental");
        tableGenre.put("3.6.3.14", "Content.Music and Dance.Background music.Sound clip");
        tableGenre.put("3.6.3.15", "Content.Music and Dance.Background music.Retro");
        tableGenre.put("3.6.4", "Content.Music and Dance.Pop-rock");
        tableGenre.put("3.6.4.1", "Content.Music and Dance.Pop-rock.Pop");
        tableGenre.put("3.6.4.2", "Content.Music and Dance.Pop-rock.Chanson/Ballad");
        tableGenre.put("3.6.4.3", "Content.Music and Dance.Pop-rock.Traditional rock and roll");
        tableGenre.put("3.6.4.4", "Content.Music and Dance.Pop-rock.Soft/Slow rock");
        tableGenre.put("3.6.4.5", "Content.Music and Dance.Pop-rock.Classic/dance/pop-rock");
        tableGenre.put("3.6.4.6", "Content.Music and Dance.Pop-rock.Folk");
        tableGenre.put("3.6.4.7", "Content.Music and Dance.Pop-rock.Punk/Funk rock");
        tableGenre.put("3.6.4.8", "Content.Music and Dance.Pop-rock.New Age");
        tableGenre.put("3.6.4.9", "Content.Music and Dance.Pop-rock.Instrumental/Band/Symphonic rock/Jam bands");
        tableGenre.put("3.6.4.10", "Content.Music and Dance.Pop-rock.Progressive/Alternative/Indie/Experimental/Art-rock");
        tableGenre.put("3.6.4.11", "Content.Music and Dance.Pop-rock.Seasonal/Holiday");
        tableGenre.put("3.6.4.12", "Content.Music and Dance.Pop-rock.Japanese pop-rock");
        tableGenre.put("3.6.4.13", "Content.Music and Dance.Pop-rock.Karaoke/Singing contests");
        tableGenre.put("3.6.5", "Content.Music and Dance.Blues/Rhythm and Blues/Soul/Gospel");
        tableGenre.put("3.6.5.1", "Content.Music and Dance.Blues/Rhythm and Blues/Soul/Gospel.Blues");
        tableGenre.put("3.6.5.2", "Content.Music and Dance.Blues/Rhythm and Blues/Soul/Gospel.R&B");
        tableGenre.put("3.6.5.3", "Content.Music and Dance.Blues/Rhythm and Blues/Soul/Gospel.Soul");
        tableGenre.put("3.6.5.4", "Content.Music and Dance.Blues/Rhythm and Blues/Soul/Gospel.Gospel");
        tableGenre.put("3.6.6", "Content.Music and Dance.Country and Western");
        tableGenre.put("3.6.7", "Content.Music and Dance.Rap/Hip Hop/Reggae");
        tableGenre.put("3.6.7.1", "Content.Music and Dance.Rap/Hip Hop/Reggae.Rap/Christian rap");
        tableGenre.put("3.6.7.2", "Content.Music and Dance.Rap/Hip Hop/Reggae.Hip Hop/Trip-Hop");
        tableGenre.put("3.6.7.3", "Content.Music and Dance.Rap/Hip Hop/Reggae.Reggae");
        tableGenre.put("3.6.7.4", "Content.Music and Dance.Rap/Hip Hop/Reggae.Ska/Gangsta");
        tableGenre.put("3.6.8", "Content.Music and Dance.Electronic/Club/Urban/Dance");
        tableGenre.put("3.6.8.1", "Content.Music and Dance.Electronic/Club/Urban/Dance.Acid/Punk/Acid Punk");
        tableGenre.put("3.6.8.2", "Content.Music and Dance.Electronic/Club/Urban/Dance.Disco");
        tableGenre.put("3.6.8.3", "Content.Music and Dance.Electronic/Club/Urban/Dance.Techno/Euro-Techno/Techno-Industrial/Industrial");
        tableGenre.put("3.6.8.4", "Content.Music and Dance.Electronic/Club/Urban/Dance.House/Techno House");
        tableGenre.put("3.6.8.5", "Content.Music and Dance.Electronic/Club/Urban/Dance.Rave");
        tableGenre.put("3.6.8.6", "Content.Music and Dance.Electronic/Club/Urban/Dance.Jungle/Tribal");
        tableGenre.put("3.6.8.7", "Content.Music and Dance.Electronic/Club/Urban/Dance.Trance");
        tableGenre.put("3.6.8.8", "Content.Music and Dance.Electronic/Club/Urban/Dance.Punk");
        tableGenre.put("3.6.8.9", "Content.Music and Dance.Electronic/Club/Urban/Dance.Garage/Psychadelic");
        tableGenre.put("3.6.8.10", "Content.Music and Dance.Electronic/Club/Urban/Dance.Metal/Death metal/Pop metal");
        tableGenre.put("3.6.8.11", "Content.Music and Dance.Electronic/Club/Urban/Dance.Drum and Bass");
        tableGenre.put("3.6.8.12", "Content.Music and Dance.Electronic/Club/Urban/Dance.Pranks");
        tableGenre.put("3.6.8.13", "Content.Music and Dance.Electronic/Club/Urban/Dance.Grunge");
        tableGenre.put("3.6.8.14", "Content.Music and Dance.Electronic/Club/Urban/Dance.Dance/Dance-pop");
        tableGenre.put("3.6.9", "Content.Music and Dance.World/Traditional/Ethnic/Folk music");
        tableGenre.put("3.6.9.1", "Content.Music and Dance.World/Traditional/Ethnic/Folk music.Africa");
        tableGenre.put("3.6.9.2", "Content.Music and Dance.World/Traditional/Ethnic/Folk music.Asia");
        tableGenre.put("3.6.9.3", "Content.Music and Dance.World/Traditional/Ethnic/Folk music.Australia/Oceania");
        tableGenre.put("3.6.9.4", "Content.Music and Dance.World/Traditional/Ethnic/Folk music.Caribbean");
        tableGenre.put("3.6.9.5", "Content.Music and Dance.World/Traditional/Ethnic/Folk music.Europe");
        tableGenre.put("3.6.9.6", "Content.Music and Dance.World/Traditional/Ethnic/Folk music.Latin America");
        tableGenre.put("3.6.9.7", "Content.Music and Dance.World/Traditional/Ethnic/Folk music.Middle East");
        tableGenre.put("3.6.9.8", "Content.Music and Dance.World/Traditional/Ethnic/Folk music.North America");
        tableGenre.put("3.6.10", "Content.Music and Dance.Hit-Chart/Song Requests ");
        tableGenre.put("3.6.11", "Content.Music and Dance.Children's Songs ");
        tableGenre.put("3.6.12", "Content.Music and Dance.Event music");
        tableGenre.put("3.6.12.1", "Content.Music and Dance.Event music.Wedding");
        tableGenre.put("3.6.12.2", "Content.Music and Dance.Event music.Sports");
        tableGenre.put("3.6.12.3", "Content.Music and Dance.Event music.Ceremonial/Chants");
        tableGenre.put("3.6.13", "Content.Music and Dance.Spoken");
        tableGenre.put("3.6.14", "Content.Music and Dance.Dance");
        tableGenre.put("3.6.14.1", "Content.Music and Dance.Dance.Ballet");
        tableGenre.put("3.6.14.2", "Content.Music and Dance.Dance.Tap");
        tableGenre.put("3.6.14.3", "Content.Music and Dance.Dance.Modern");
        tableGenre.put("3.6.14.4", "Content.Music and Dance.Dance.Classical");
        tableGenre.put("3.7", "Content.Interactive Games");
        tableGenre.put("3.7.1", "Content.Interactive Games.Content games categories");
        tableGenre.put("3.7.1.1", "Content.Interactive Games.Content games categories.Action");
        tableGenre.put("3.7.1.2", "Content.Interactive Games.Content games categories.Adventure");
        tableGenre.put("3.7.1.3", "Content.Interactive Games.Content games categories.Fighting");
        tableGenre.put("3.7.1.4", "Content.Interactive Games.Content games categories.Online");
        tableGenre.put("3.7.1.5", "Content.Interactive Games.Content games categories.Platform");
        tableGenre.put("3.7.1.6", "Content.Interactive Games.Content games categories.Puzzle");
        tableGenre.put("3.7.1.7", "Content.Interactive Games.Content games categories.RPG/MUDs");
        tableGenre.put("3.7.1.8", "Content.Interactive Games.Content games categories.Racing");
        tableGenre.put("3.7.1.9", "Content.Interactive Games.Content games categories.Simulation");
        tableGenre.put("3.7.1.10", "Content.Interactive Games.Content games categories.Sports");
        tableGenre.put("3.7.1.11", "Content.Interactive Games.Content games categories.Strategy");
        tableGenre.put("3.7.1.12", "Content.Interactive Games.Content games categories.Wrestling");
        tableGenre.put("3.7.1.13", "Content.Interactive Games.Content games categories.Classic/Retro");
        tableGenre.put("3.8.1.14", "Content.Interactive Games.Content games categories.Other");
        tableGenre.put("3.7.2", "Content.Interactive Games.Style");
        tableGenre.put("3.7.2.1", "Content.Interactive Games.Style.Logic based");
        tableGenre.put("3.7.2.2", "Content.Interactive Games.Style.Word games");
        tableGenre.put("3.7.2.3", "Content.Interactive Games.Style.Positional");
        tableGenre.put("3.7.2.4", "Content.Interactive Games.Style.Board games");
        tableGenre.put("3.7.2.5", "Content.Interactive Games.Style.Text environments");
        tableGenre.put("3.7.2.6", "Content.Interactive Games.Style.Dynamic 2D/3D graphics");
        tableGenre.put("3.7.2.7", "Content.Interactive Games.Style.Non-linear video");

        // Intended audience tableGenre
        tableGenre.put("4", "Intended audience");
        tableGenre.put("4.1", "Intended audience.General audience");
        tableGenre.put("4.2", "Intended audience.Age groups");
        tableGenre.put("4.2.1", "Intended audience.Age groups.Children");
        tableGenre.put("4.2.1.1", "Intended audience.Age groups.Children.Age 4-7");
        tableGenre.put("4.2.1.2", "Intended audience.Age groups.Children.Age 8-13");
        tableGenre.put("4.2.1.3", "Intended audience.Age groups.Children.Age 14-15");
        tableGenre.put("4.2.2", "Intended audience.Age groups.Young Adults");
        tableGenre.put("4.2.2.1", "Intended audience.Age groups.Young Adults.Age 16-17");
        tableGenre.put("4.2.2.2", "Intended audience.Age groups.Young Adults.Age 18-20");
        tableGenre.put("4.2.2.3", "Intended audience.Age groups.Young Adults.Age 21-24");
        tableGenre.put("4.2.3", "Intended audience.Age groups.Adults");
        tableGenre.put("4.2.3.1", "Intended audience.Age groups.Adults.Age 25-34");
        tableGenre.put("4.2.3.2", "Intended audience.Age groups.Adults.Age 35-44");
        tableGenre.put("4.2.3.3", "Intended audience.Age groups.Adults.Age 45-54");
        tableGenre.put("4.2.3.4", "Intended audience.Age groups.Adults.Age 55-64");
        tableGenre.put("4.2.3.5", "Intended audience.Age groups.Adults.Age 65+");
        tableGenre.put("4.2.3.6", "Intended audience.Age groups.Adults.Specific single age");
        tableGenre.put("4.2.4", "Intended audience.Age groups.All ages");
        tableGenre.put("4.3", "Intended audience.Social groups");
        tableGenre.put("4.3.1", "Intended audience.Social groups.Ethnic");
        tableGenre.put("4.3.1.1", "Intended audience.Social groups.Ethnic.Immigrant groups");
        tableGenre.put("4.3.1.2", "Intended audience.Social groups.Ethnic.Indiginous");
        tableGenre.put("4.3.2", "Intended audience.Social groups.Religious");
        tableGenre.put("4.4", "Intended audience.Occupational groups");
        tableGenre.put("4.4.1", "Intended audience.Occupational groups.AB");
        tableGenre.put("4.4.1.1", "Intended audience.Occupational groups.AB.A");
        tableGenre.put("4.4.1.2", "Intended audience.Occupational groups.AB.B");
        tableGenre.put("4.4.2", "Intended audience.Occupational groups.C1C2");
        tableGenre.put("4.4.2.1", "Intended audience.Occupational groups.C1C2.C1");
        tableGenre.put("4.4.2.2", "Intended audience.Occupational groups.C1C2.C2");
        tableGenre.put("4.4.3", "Intended audience.Occupational groups.DE");
        tableGenre.put("4.4.3.1", "Intended audience.Occupational groups.DE.D");
        tableGenre.put("4.4.3.2", "Intended audience.Occupational groups.DE.E");
        tableGenre.put("4.5", "Intended audience.Other special interest/Occupational groups");
        tableGenre.put("4.6", "Intended audience.Gender");
        tableGenre.put("4.6.1", "Intended audience.Gender.Primarily for males");
        tableGenre.put("4.6.2", "Intended audience.Gender.Primarily for females");
        tableGenre.put("4.6.3", "Intended audience.Gender.For males and females");
        tableGenre.put("4.7", "Intended audience.Geographical");
        tableGenre.put("4.7.1", "Intended audience.Geographical.Universal");
        tableGenre.put("4.7.2", "Intended audience.Geographical.Continental");
        tableGenre.put("4.7.3", "Intended audience.Geographical.National");
        tableGenre.put("4.7.4", "Intended audience.Geographical.Regional");
        tableGenre.put("4.7.5", "Intended audience.Geographical.Local");
        tableGenre.put("4.8", "Intended audience.Education level");
        tableGenre.put("4.8.1", "Intended audience.Education level.Primary");
        tableGenre.put("4.8.2", "Intended audience.Education level.Secondary");
        tableGenre.put("4.8.3", "Intended audience.Education level.Tertiary");
        tableGenre.put("4.8.4", "Intended audience.Education level.Post Graduate/Life-long learning");
        tableGenre.put("4.9", "Intended audience.Lifestyle stages");
        tableGenre.put("4.9.1", "Intended audience.Lifestyle stages.Single");
        tableGenre.put("4.9.2", "Intended audience.Lifestyle stages.Couple");
        tableGenre.put("4.9.3", "Intended audience.Lifestyle stages.Family with Children 0-3");
        tableGenre.put("4.9.4", "Intended audience.Lifestyle stages.Family with Children 4-7");
        tableGenre.put("4.9.5", "Intended audience.Lifestyle stages.Family with Children 8-15");
        tableGenre.put("4.9.6", "Intended audience.Lifestyle stages.Family with Children 16+");
        tableGenre.put("4.9.7", "Intended audience.Lifestyle stages.Empty Nester");
        tableGenre.put("4.9.8", "Intended audience.Lifestyle stages.Retired");

        // Origination tableGenre
        tableGenre.put("5", "Origination");
        tableGenre.put("5.1", "Origination.Studio");
        tableGenre.put("5.1.1", "Origination.Studio.Live");
        tableGenre.put("5.1.2", "Origination.Studio.As live");
        tableGenre.put("5.1.3", "Origination.Studio.Edited");
        tableGenre.put("5.2", "Origination.Made on location");
        tableGenre.put("5.2.1", "Origination.Made on location.Live");
        tableGenre.put("5.2.2", "Origination.Made on location.As live");
        tableGenre.put("5.2.3", "Origination.Made on location.Edited");
        tableGenre.put("5.3", "Origination.Cinema industry originated");
        tableGenre.put("5.4", "Origination.Made on film");
        tableGenre.put("5.5", "Origination.Home video");
        tableGenre.put("5.6", "Origination.Multimedia format");

        // Content alert tableGenre
        tableGenre.put("6", "Content alert");
        tableGenre.put("6.0", "Content alert.Alert not required");
        tableGenre.put("6.0.1", "Content alert.Alert not required.No content that requires alerting in any of the categories below");
        tableGenre.put("6.1", "Content alert.Sex");
        tableGenre.put("6.1.1", "Content alert.Sex.No sex descriptors");
        tableGenre.put("6.1.2", "Content alert.Sex.Obscured or implied sexual activity");
        tableGenre.put("6.1.3", "Content alert.Sex.Frank portrayal of sex and sexuality");
        tableGenre.put("6.1.4", "Content alert.Sex.Scenes of explicit sexual behaviour suitable for adults only");
        tableGenre.put("6.1.5", "Content alert.Sex.Sexual Violence");
        tableGenre.put("6.2", "Content alert.Nudity");
        tableGenre.put("6.2.1", "Content alert.Nudity.No nudity descriptors");
        tableGenre.put("6.2.2", "Content alert.Nudity.Partial nudity");
        tableGenre.put("6.2.3", "Content alert.Nudity.Full frontal nudity");
        tableGenre.put("6.3", "Content alert.Violence - Human Beings");
        tableGenre.put("6.3.1", "Content alert.Violence - Human Beings.No violence descriptors human beings");
        tableGenre.put("6.3.2", "Content alert.Violence - Human Beings.Deliberate infliction of pain to human beings");
        tableGenre.put("6.3.3", "Content alert.Violence - Human Beings.Infliction of strong psychological or physical pain to human beings");
        tableGenre.put("6.3.4", "Content alert.Violence - Human Beings.Deliberate killing of human beings");
        tableGenre.put("6.4", "Content alert.Violence - Animals");
        tableGenre.put("6.4.1", "Content alert.Violence - Animals.No violence descriptors animals");
        tableGenre.put("6.4.2", "Content alert.Violence - Animals.Deliberate infliction of pain to animals");
        tableGenre.put("6.4.3", "Content alert.Violence - Animals.Deliberate killing of animals");
        tableGenre.put("6.5", "Content alert.Violence - Fantasy Characters");
        tableGenre.put("6.5.1", "Content alert.Violence - Fantasy Characters.No violence descriptors");
        tableGenre.put("6.5.2", "Content alert.Violence - Fantasy Characters.Deliberate infliction of pain to fantasy characters (including animation)");
        tableGenre.put("6.5.3", "Content alert.Violence - Fantasy Characters.Deliberate killing of fantasy characters (including animation)");
        tableGenre.put("6.6", "Content alert.Language");
        tableGenre.put("6.6.1", "Content alert.Language.No language descriptors");
        tableGenre.put("6.6.2", "Content alert.Language.Occasional use of mild swear words and profanities");
        tableGenre.put("6.6.3", "Content alert.Language.Frequent use of mild swear words and profanities");
        tableGenre.put("6.6.4", "Content alert.Language.Occasional use of very strong language");
        tableGenre.put("6.6.5", "Content alert.Language.Frequent use of very strong language");
        tableGenre.put("6.7", "Content alert.Disturbing Scenes");
        tableGenre.put("6.7.1", "Content alert.Disturbing Scenes.No disturbing scenes descriptors");
        tableGenre.put("6.7.2", "Content alert.Disturbing Scenes.Factual material that may cause distress");
        tableGenre.put("6.7.3", "Content alert.Disturbing Scenes.Mild scenes of blood and gore");
        tableGenre.put("6.7.4", "Content alert.Disturbing Scenes.Severe scenes of blood and gore");
        tableGenre.put("6.7.5", "Content alert.Disturbing Scenes.Scenes with extreme horror effects");
        tableGenre.put("6.8", "Content alert.Discrimination");
        tableGenre.put("6.8.1", "Content alert.Discrimination.No discrimination descriptors");
        tableGenre.put("6.8.2", "Content alert.Discrimination.Deliberate discrimination or the portrayal of deliberate discrimination");
        tableGenre.put("6.9", "Content alert.Illegal Drugs");
        tableGenre.put("6.9.1", "Content alert.Illegal Drugs.No illegal drugs descriptors");
        tableGenre.put("6.9.2", "Content alert.Illegal Drugs.Portrayal of illegal drug use");
        tableGenre.put("6.9.3", "Content alert.Illegal Drugs.Portrayal of illegal drug use with instructive detail");
        tableGenre.put("6.10", "Content alert.Strobing");
        tableGenre.put("6.10.1", "Content alert.Strobing.No strobing");
        tableGenre.put("6.10.2", "Content alert.Strobing.Strobing that could impact on those suffering from Photosensitive epilepsy");

        // Media type tableGenre
        tableGenre.put("7", "Media type");
        tableGenre.put("7.1", "Media type.Linear");
        tableGenre.put("7.1.1", "Media type.Linear.Audio only");
        tableGenre.put("7.1.2", "Media type.Linear.Video only");
        tableGenre.put("7.1.3", "Media type.Linear.Audio and video");
        tableGenre.put("7.1.4", "Media type.Linear.Multimedia");
        tableGenre.put("7.1.4.1", "Media type.Linear.Multimedia.Text");
        tableGenre.put("7.1.4.2", "Media type.Linear.Multimedia.Graphics");
        tableGenre.put("7.1.4.3", "Media type.Linear.Multimedia.Application");
        tableGenre.put("7.2", "Media type.Non-linear");
        tableGenre.put("7.2.1", "Media type.Non-linear.Audio only");
        tableGenre.put("7.2.2", "Media type.Non-linear.Video only");
        tableGenre.put("7.2.3", "Media type.Non-linear.Audio and video");
        tableGenre.put("7.2.4", "Media type.Non-linear.Multimedia");
        tableGenre.put("7.2.4.1", "Media type.Non-linear.Multimedia.Text");
        tableGenre.put("7.2.4.2", "Media type.Non-linear.Multimedia.Graphics");
        tableGenre.put("7.2.4.3", "Media type.Non-linear.Multimedia.Application");
        tableGenre.put("7.3", "Media type.Audio video enhancements");
        tableGenre.put("7.3.1", "Media type.Audio video enhancements.Linear with non-sync");
        tableGenre.put("7.3.2", "Media type.Audio video enhancements.Linear with sync");
        tableGenre.put("7.3.3", "Media type.Audio video enhancements.Multi stream audio");
        tableGenre.put("7.3.4", "Media type.Audio video enhancements.Multi stream video");
        tableGenre.put("7.3.5", "Media type.Audio video enhancements.Non-linear one stream AV show");
        tableGenre.put("7.3.6", "Media type.Audio video enhancements.Non-linear multi stream");
        tableGenre.put("7.3.7", "Media type.Audio video enhancements.Hybrid NVOD");
        tableGenre.put("7.3.8", "Media type.Audio video enhancements.Mix and match");
        tableGenre.put("7.3.9", "Media type.Audio video enhancements.Parallel 'layer controlled' audio or video support");
        tableGenre.put("7.3.10", "Media type.Audio video enhancements.Linear broadcast with online insertions");
        tableGenre.put("7.3.11", "Media type.Audio video enhancements.Other");

        // Atmosphere tableGenre
        tableGenre.put("8", "Atmosphere");
        tableGenre.put("8.1", "Atmosphere.Alternative");
        tableGenre.put("8.2", "Atmosphere.Analytical");
        tableGenre.put("8.3", "Atmosphere.Astonishing");
        tableGenre.put("8.4", "Atmosphere.Ambitious");
        tableGenre.put("8.5", "Atmosphere.Black");
        tableGenre.put("8.6", "Atmosphere.Breathtaking");
        tableGenre.put("8.7", "Atmosphere.Chilling");
        tableGenre.put("8.8", "Atmosphere.Coarse");
        tableGenre.put("8.9", "Atmosphere.Compelling");
        tableGenre.put("8.10", "Atmosphere.Confrontational");
        tableGenre.put("8.11", "Atmosphere.Contemporary");
        tableGenre.put("8.12", "Atmosphere.Crazy");
        tableGenre.put("8.13", "Atmosphere.Cutting edge");
        tableGenre.put("8.14", "Atmosphere.Eclectic");
        tableGenre.put("8.15", "Atmosphere.Edifying");
        tableGenre.put("8.16", "Atmosphere.Exciting");
        tableGenre.put("8.17", "Atmosphere.Fast-moving");
        tableGenre.put("8.18", "Atmosphere.Frantic");
        tableGenre.put("8.19", "Atmosphere.Fun");
        tableGenre.put("8.20", "Atmosphere.Gripping");
        tableGenre.put("8.21", "Atmosphere.Gritty");
        tableGenre.put("8.22", "Atmosphere.Gutsy");
        tableGenre.put("8.23", "Atmosphere.Happy");
        tableGenre.put("8.24", "Atmosphere.Heart-rending");
        tableGenre.put("8.25", "Atmosphere.Heart warming");
        tableGenre.put("8.26", "Atmosphere.Hot");
        tableGenre.put("8.27", "Atmosphere.Humorous");
        tableGenre.put("8.28", "Atmosphere.Innovative");
        tableGenre.put("8.29", "Atmosphere.Insightful");
        tableGenre.put("8.30", "Atmosphere.Inspirational");
        tableGenre.put("8.31", "Atmosphere.Intriguing");
        tableGenre.put("8.32", "Atmosphere.Irreverant");
        tableGenre.put("8.33", "Atmosphere.Laid back");
        tableGenre.put("8.34", "Atmosphere.Outrageous");
        tableGenre.put("8.35", "Atmosphere.Peaceful");
        tableGenre.put("8.36", "Atmosphere.Powerful");
        tableGenre.put("8.37", "Atmosphere.Practical");
        tableGenre.put("8.38", "Atmosphere.Rollercoaster");
        tableGenre.put("8.39", "Atmosphere.Romantic");
        tableGenre.put("8.40", "Atmosphere.Rousing");
        tableGenre.put("8.41", "Atmosphere.Sad");
        tableGenre.put("8.42", "Atmosphere.Satirical");
        tableGenre.put("8.43", "Atmosphere.Serious");
        tableGenre.put("8.44", "Atmosphere.Sexy");
        tableGenre.put("8.45", "Atmosphere.Shocking");
        tableGenre.put("8.46", "Atmosphere.Silly");
        tableGenre.put("8.47", "Atmosphere.Spooky");
        tableGenre.put("8.48", "Atmosphere.Stunning");
        tableGenre.put("8.49", "Atmosphere.Stylish");
        tableGenre.put("8.50", "Atmosphere.Terrifying");
        tableGenre.put("8.51", "Atmosphere.Thriller");
        tableGenre.put("8.52", "Atmosphere.Violent");
        tableGenre.put("8.53", "Atmosphere.Wacky");

    }

}
